In [2]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
import re
import spacy
import pandas as pd

In [6]:
para = "Bengaluru is now the leading hub for India's youngest founders, with 21 entrepreneurs from the city featuring on the Avendus Wealth - Hurun India U30 List 2026, up from just 7 last year, Priyank Kharge, Minister of Home, e-Governance, Electronics, IT & BT, Government of Karnataka, said.Kharge cited the report to highlight a broader shift in India's innovation landscape. According to the Avendus Wealth - Hurun India U30 List 2026, which recognises 102 exceptional leaders aged 30 and under, 18 of the companies on the list are headquartered in Bengaluru -- the highest for any city in the country. The list brings together first-generation founders building ventures valued at USD 25 million or more and next-generation leaders driving family-owned businesses valued at USD 50 million or more.The list reflects how Bengaluru continues to lead from the front, Kharge said. This is a testament to Bengaluru's entrepreneurial spirit, world-class talent and collaborative innovation ecosystem.The report points to a clear pivot toward DeepTech and HardTech. One in four entrants on this year's list of 27 founders, came from DeepTech and HardTech sectors, including AI & ML, EV & Auto Components, SpaceTech, Aerospace & Defence and Cybersecurity. The number of entrepreneurs from AI and Machine Learning ventures has nearly doubled this year to 8, while SpaceTech features 6 founders across Pixxel, Digantara and Apolink. The Automobile & Auto Components sector also doubled to 7 entrants, with all new entrants focused on electric vehicles or components."
print(para)

Bengaluru is now the leading hub for India's youngest founders, with 21 entrepreneurs from the city featuring on the Avendus Wealth - Hurun India U30 List 2026, up from just 7 last year, Priyank Kharge, Minister of Home, e-Governance, Electronics, IT & BT, Government of Karnataka, said.Kharge cited the report to highlight a broader shift in India's innovation landscape. According to the Avendus Wealth - Hurun India U30 List 2026, which recognises 102 exceptional leaders aged 30 and under, 18 of the companies on the list are headquartered in Bengaluru -- the highest for any city in the country. The list brings together first-generation founders building ventures valued at USD 25 million or more and next-generation leaders driving family-owned businesses valued at USD 50 million or more.The list reflects how Bengaluru continues to lead from the front, Kharge said. This is a testament to Bengaluru's entrepreneurial spirit, world-class talent and collaborative innovation ecosystem.The report points to a clear pivot toward DeepTech and HardTech. One in four entrants on this year's list of 27 founders, came from DeepTech and HardTech sectors, including AI & ML, EV & Auto Components, SpaceTech, Aerospace & Defence and Cybersecurity. The number of entrepreneurs from AI and Machine Learning ventures has nearly doubled this year to 8, while SpaceTech features 6 founders across Pixxel, Digantara and Apolink. The Automobile & Auto Components sector also doubled to 7 entrants, with all new entrants focused on electric vehicles or components.

In [7]:
para.lower()

"bengaluru is now the leading hub for india's youngest founders, with 21 entrepreneurs from the city featuring on the avendus wealth - hurun india u30 list 2026, up from just 7 last year, priyank kharge, minister of home, e-governance, electronics, it & bt, government of karnataka, said.kharge cited the report to highlight a broader shift in india's innovation landscape. according to the avendus wealth - hurun india u30 list 2026, which recognises 102 exceptional leaders aged 30 and under, 18 of the companies on the list are headquartered in bengaluru -- the highest for any city in the country. the list brings together first-generation founders building ventures valued at usd 25 million or more and next-generation leaders driving family-owned businesses valued at usd 50 million or more.the list reflects how bengaluru continues to lead from the front, kharge said. this is a testament to bengaluru's entrepreneurial spirit, world-class talent and collaborative innovation ecosystem.the report points to a clear pivot toward deeptech and hardtech. one in four entrants on this year's list of 27 founders, came from deeptech and hardtech sectors, including ai & ml, ev & auto components, spacetech, aerospace & defence and cybersecurity. the number of entrepreneurs from ai and machine learning ventures has nearly doubled this year to 8, while spacetech features 6 founders across pixxel, digantara and apolink. the automobile & auto components sector also doubled to 7 entrants, with all new entrants focused on electric vehicles or components."

In [9]:
data = pd.DataFrame({'text': [para]})
data.head()

                                                text
0  Bengaluru is now the leading hub for India's y...

In [10]:
data['text_lowercase'] = data['text'].str.lower()
data.head()

,text,text_lowercase
0,Bengaluru is now the leading hub for India's y...,bengaluru is now the leading hub for india's y...

In [12]:
data['text_no_punct'] = data.apply(lambda x: re.sub(r'[^\w\s]', '', x['text_lowercase']), axis = 1)
data.head()

,text,text_lowercase,text_no_punct
0,Bengaluru is now the leading hub for India's y...,bengaluru is now the leading hub for india's y...,bengaluru is now the leading hub for indias yo...

In [13]:
en_stopwords = stopwords.words('english')

In [15]:
data['text_no_punct_no_stopwords'] = data['text_no_punct'].apply(lambda x: ' '.join([word for word in x.split() if word not in (en_stopwords)]))
data['text_no_punct_no_stopwords'][0]

'bengaluru leading hub indias youngest founders 21 entrepreneurs city featuring avendus wealth hurun india u30 list 2026 7 last year priyank kharge minister home egovernance electronics bt government karnataka saidkharge cited report highlight broader shift indias innovation landscape according avendus wealth hurun india u30 list 2026 recognises 102 exceptional leaders aged 30 18 companies list headquartered bengaluru highest city country list brings together firstgeneration founders building ventures valued usd 25 million nextgeneration leaders driving familyowned businesses valued usd 50 million morethe list reflects bengaluru continues lead front kharge said testament bengalurus entrepreneurial spirit worldclass talent collaborative innovation ecosystemthe report points clear pivot toward deeptech hardtech one four entrants years list 27 founders came deeptech hardtech sectors including ai ml ev auto components spacetech aerospace defence cybersecurity number entrepreneurs ai machine learning ventures nearly doubled year 8 spacetech features 6 founders across pixxel digantara apolink automobile auto components sector also doubled 7 entrants new entrants focused electric vehicles components'

In [16]:
data['text_tokens'] = data.apply(lambda x: word_tokenize(x['text_no_punct_no_stopwords']), axis = 1)
data['text_tokens'][0]

['bengaluru',
 'leading',
 'hub',
 'indias',
 'youngest',
 'founders',
 '21',
 'entrepreneurs',
 'city',
 'featuring',
 'avendus',
 'wealth',
 'hurun',
 'india',
 'u30',
 'list',
 '2026',
 '7',
 'last',
 'year',
 'priyank',
 'kharge',
 'minister',
 'home',
 'egovernance',
 'electronics',
 'bt',
 'government',
 'karnataka',
 'saidkharge',
 'cited',
 'report',
 'highlight',
 'broader',
 'shift',
 'indias',
 'innovation',
 'landscape',
 'according',
 'avendus',
 'wealth',
 'hurun',
 'india',
 'u30',
 'list',
 '2026',
 'recognises',
 '102',
 'exceptional',
 'leaders',
 'aged',
 '30',
 '18',
 'companies',
 'list',
 'headquartered',
 'bengaluru',
 'highest',
 'city',
 'country',
 'list',
 'brings',
 'together',
 'firstgeneration',
 'founders',
 'building',
 'ventures',
 'valued',
 'usd',
 '25',
 'million',
 'nextgeneration',
 'leaders',
 'driving',
 'familyowned',
 'businesses',
 'valued',
 'usd',
 '50',
 'million',
 'morethe',
 'list',
 'reflects',
 'bengaluru',
 'continues',
 'lead',
 'front',
 'kharge',
 'said',
 'testament',
 'bengalurus',
 'entrepreneurial',
 'spirit',
 'worldclass',
 'talent',
 'collaborative',
 'innovation',
 'ecosystemthe',
 'report',
 'points',
 'clear',
 'pivot',
 'toward',
 'deeptech',
 'hardtech',
 'one',
 'four',
 'entrants',
 'years',
 'list',
 '27',
 'founders',
 'came',
 'deeptech',
 'hardtech',
 'sectors',
 'including',
 'ai',
 'ml',
 'ev',
 'auto',
 'components',
 'spacetech',
 'aerospace',
 'defence',
 'cybersecurity',
 'number',
 'entrepreneurs',
 'ai',
 'machine',
 'learning',
 'ventures',
 'nearly',
 'doubled',
 'year',
 '8',
 'spacetech',
 'features',
 '6',
 'founders',
 'across',
 'pixxel',
 'digantara',
 'apolink',
 'automobile',
 'auto',
 'components',
 'sector',
 'also',
 'doubled',
 '7',
 'entrants',
 'new',
 'entrants',
 'focused',
 'electric',
 'vehicles',
 'components']

In [19]:
lemmatizer = WordNetLemmatizer()
data['tokens_lemmatized'] = data['text_tokens'].apply(lambda tokens: [lemmatizer.lemmatize(token) for token in tokens])
data['tokens_lemmatized'][0]

['bengaluru',
 'leading',
 'hub',
 'india',
 'youngest',
 'founder',
 '21',
 'entrepreneur',
 'city',
 'featuring',
 'avendus',
 'wealth',
 'hurun',
 'india',
 'u30',
 'list',
 '2026',
 '7',
 'last',
 'year',
 'priyank',
 'kharge',
 'minister',
 'home',
 'egovernance',
 'electronics',
 'bt',
 'government',
 'karnataka',
 'saidkharge',
 'cited',
 'report',
 'highlight',
 'broader',
 'shift',
 'india',
 'innovation',
 'landscape',
 'according',
 'avendus',
 'wealth',
 'hurun',
 'india',
 'u30',
 'list',
 '2026',
 'recognises',
 '102',
 'exceptional',
 'leader',
 'aged',
 '30',
 '18',
 'company',
 'list',
 'headquartered',
 'bengaluru',
 'highest',
 'city',
 'country',
 'list',
 'brings',
 'together',
 'firstgeneration',
 'founder',
 'building',
 'venture',
 'valued',
 'usd',
 '25',
 'million',
 'nextgeneration',
 'leader',
 'driving',
 'familyowned',
 'business',
 'valued',
 'usd',
 '50',
 'million',
 'morethe',
 'list',
 'reflects',
 'bengaluru',
 'continues',
 'lead',
 'front',
 'kharge',
 'said',
 'testament',
 'bengalurus',
 'entrepreneurial',
 'spirit',
 'worldclass',
 'talent',
 'collaborative',
 'innovation',
 'ecosystemthe',
 'report',
 'point',
 'clear',
 'pivot',
 'toward',
 'deeptech',
 'hardtech',
 'one',
 'four',
 'entrant',
 'year',
 'list',
 '27',
 'founder',
 'came',
 'deeptech',
 'hardtech',
 'sector',
 'including',
 'ai',
 'ml',
 'ev',
 'auto',
 'component',
 'spacetech',
 'aerospace',
 'defence',
 'cybersecurity',
 'number',
 'entrepreneur',
 'ai',
 'machine',
 'learning',
 'venture',
 'nearly',
 'doubled',
 'year',
 '8',
 'spacetech',
 'feature',
 '6',
 'founder',
 'across',
 'pixxel',
 'digantara',
 'apolink',
 'automobile',
 'auto',
 'component',
 'sector',
 'also',
 'doubled',
 '7',
 'entrant',
 'new',
 'entrant',
 'focused',
 'electric',
 'vehicle',
 'component']

In [20]:
new_df = pd.DataFrame(columns=['tokens_cl', 'pos_tags'])
new_df.head()

Empty DataFrame
Columns: [tokens_cl, pos_tags]
Index: []

In [21]:
nlp = spacy.load('en_core_web_sm')

In [24]:
data['final_tokens'] = data['tokens_lemmatized'].apply(lambda x: ' '.join(x))
data.head()

,text,text_lowercase,text_no_punct,text_no_punct_no_stopwords,text_tokens,tokens_lemmatized,final_tokens
0,Bengaluru is now the leading hub for India's y...,bengaluru is now the leading hub for india's y...,bengaluru is now the leading hub for indias yo...,bengaluru leading hub indias youngest founders...,"[bengaluru, leading, hub, indias, youngest, fo...","[bengaluru, leading, hub, india, youngest, fou...",bengaluru leading hub india youngest founder 2...

In [27]:
final_tokens_list = sum(data['tokens_lemmatized'], [])
print(final_tokens_list)

['bengaluru', 'leading', 'hub', 'india', 'youngest', 'founder', '21', 'entrepreneur', 'city', 'featuring', 'avendus', 'wealth', 'hurun', 'india', 'u30', 'list', '2026', '7', 'last', 'year', 'priyank', 'kharge', 'minister', 'home', 'egovernance', 'electronics', 'bt', 'government', 'karnataka', 'saidkharge', 'cited', 'report', 'highlight', 'broader', 'shift', 'india', 'innovation', 'landscape', 'according', 'avendus', 'wealth', 'hurun', 'india', 'u30', 'list', '2026', 'recognises', '102', 'exceptional', 'leader', 'aged', '30', '18', 'company', 'list', 'headquartered', 'bengaluru', 'highest', 'city', 'country', 'list', 'brings', 'together', 'firstgeneration', 'founder', 'building', 'venture', 'valued', 'usd', '25', 'million', 'nextgeneration', 'leader', 'driving', 'familyowned', 'business', 'valued', 'usd', '50', 'million', 'morethe', 'list', 'reflects', 'bengaluru', 'continues', 'lead', 'front', 'kharge', 'said', 'testament', 'bengalurus', 'entrepreneurial', 'spirit', 'worldclass', 'talent', 'collaborative', 'innovation', 'ecosystemthe', 'report', 'point', 'clear', 'pivot', 'toward', 'deeptech', 'hardtech', 'one', 'four', 'entrant', 'year', 'list', '27', 'founder', 'came', 'deeptech', 'hardtech', 'sector', 'including', 'ai', 'ml', 'ev', 'auto', 'component', 'spacetech', 'aerospace', 'defence', 'cybersecurity', 'number', 'entrepreneur', 'ai', 'machine', 'learning', 'venture', 'nearly', 'doubled', 'year', '8', 'spacetech', 'feature', '6', 'founder', 'across', 'pixxel', 'digantara', 'apolink', 'automobile', 'auto', 'component', 'sector', 'also', 'doubled', '7', 'entrant', 'new', 'entrant', 'focused', 'electric', 'vehicle', 'component']

In [28]:
spacy_docs_tokens = nlp(' '.join(final_tokens_list))

In [30]:
for word in spacy_docs_tokens:
    new_df = pd.concat([new_df, pd.DataFrame.from_records([{'tokens_cl': word.text, 'pos_tags': word.pos_}])], ignore_index=True)
new_df.head(20)

       tokens_cl pos_tags
0      bengaluru    PROPN
1        leading     VERB
2            hub     NOUN
3          india    PROPN
4       youngest      ADJ
5        founder     NOUN
6             21      NUM
7   entrepreneur     NOUN
8           city     NOUN
9      featuring     VERB
10       avendus    PROPN
11        wealth    PROPN
12         hurun    PROPN
13         india    PROPN
14           u30    PROPN
15          list     NOUN
16          2026      NUM
17             7      NUM
18          last      ADJ
19          year     NOUN

In [31]:
new_df_counts = new_df.groupby(['tokens_cl', 'pos_tags']).size().reset_index(name='counts').sort_values(by='counts', ascending = False)
new_df_counts.head(20)

        tokens_cl pos_tags  counts
83           list     NOUN       6
59        founder     NOUN       4
71          india    PROPN       4
23      bengaluru    PROPN       3
36      component     NOUN       3
49        entrant      ADJ       3
119          year     NOUN       3
116       venture     NOUN       2
85        million      NUM       2
32           city     NOUN       2
2            2026      NUM       2
103        sector     NOUN       2
40       deeptech      ADJ       2
19           auto     NOUN       2
63       hardtech     NOUN       2
69          hurun    PROPN       2
80         leader     NOUN       2
43        doubled     VERB       2
117        wealth    PROPN       2
50   entrepreneur     NOUN       2

In [32]:
new_df_ner = pd.DataFrame(columns=['tokens_cl', 'ner_tags'])

In [36]:
for word in spacy_docs_tokens.ents:
    if pd.isna(word.label_) is False:
        new_df_ner = pd.concat([new_df_ner, pd.DataFrame.from_records([{'tokens_cl': word.text, 'ner_tags': word.label_}])], ignore_index = True)
new_df_ner.head(20)

                         tokens_cl  ner_tags
0                        bengaluru       GPE
1                   india youngest       ORG
2                               21  CARDINAL
3                entrepreneur city       GPE
4                            india       GPE
5                           2026 7      DATE
6                        last year      DATE
7                            india       GPE
8                            india       GPE
9                             2026      DATE
10                             102  CARDINAL
11                           30 18      DATE
12  bengaluru highest city country       ORG
13                      25 million  CARDINAL
14                      50 million  CARDINAL
15               deeptech hardtech       ORG
16                        one four      DATE
17                              27  CARDINAL
18               deeptech hardtech       ORG
19                               6  CARDINAL